### PR TITLE
Added ability to quit from LogInWindow.

### PR DESCRIPTION
**Pull request by chrisledet**
Noticed that the login window didn't have a way to quit so I added it.

screen

### CODE REVIEW

**Comment by dcramer** [comment]
+1, had to kill it to restart it earlier

**Comment by fphilipe** [comment]
Doesn't cmd+Q work for you guys?

**Comment by markrickert** [comment]
`CMD+Q` works but isn't very intuitive for a menu item.

**Comment by maddox** [comment]
:-1: that takes a whole extra interaction to even get to that view to quit, vs command-q.

We'll get quit in the menu when we get a menu.

**Pull request closed without merging**
